server:
  port: 8130 # 服务端口

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tSPSqEpCAjCACKwZowA
    keySecret: KG8NCuv9Hus1W4k4kLaoUzd73Wmexv
    bucketName: srb-file-199909