server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名

  #使用Springboot自带的发送邮件方式替代短信验证
  mail:
    # 配置邮件编码
    default-encoding: UTF-8
    # 配置 smtp 服务器地址
    host: smtp.qq.com
    # 配置申请到的授权码
    password: bspwwlvshfmncadh
    # smtp 服务器的端口
    port: 587
    properties:
      mail:
        # 表示开启 DEBUG 模式
        debug: true
        smtp:
          # 配饰 SSL 加密工厂
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
    # 配置邮箱用户名
    username: 319111721@qq.com

  redis:
    host: 192.168.5.136
    port: 6379
    database: 0
#    password: 123456 #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

  rabbitmq:
    host: 192.168.5.136
    port: 5672
    virtual-host: /srbhost200921
    username: srb200921
    password: 123456

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  sentinel:
    enabled: true #开启Feign对Sentinel的支持

logging:
  level:
    com.atguigu.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口